"""Add parent_id

Revision ID: 2d0526369f91
Revises: c34f09b437e0
Create Date: 2026-08-14 01:05:20.743437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0526369f91'
down_revision: Union[str, Sequence[str], None] = 'c34f09b437e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_documents_parent_id', 'documents', ['parent_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'parent_id')
    # ### end Alembic commands ###
