"""Added connected_account column in the Users table

Revision ID: 3792a4ab502b
Revises: f0e6a6b9b182
Create Date: 2026-08-08 21:12:49.599393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3792a4ab502b'
down_revision: Union[str, Sequence[str], None] = 'f0e6a6b9b182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('connected_account', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'connected_account')
    # ### end Alembic commands ###
