"""Added CTA column in the processed_documents_modal

Revision ID: 40ef61d998d6
Revises: 2d0526369f91
Create Date: 2026-08-14 11:05:16.472217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ef61d998d6'
down_revision: Union[str, Sequence[str], None] = '2d0526369f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_to_action', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_documents', schema=None) as batch_op:
        batch_op.drop_column('call_to_action')

    # ### end Alembic commands ###
