"""add file path and processing status to documents

Revision ID: f0e6a6b9b182
Revises: 07208e7aa54e
Create Date: 2026-08-07 13:35:19.242266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e6a6b9b182'
down_revision: Union[str, Sequence[str], None] = '07208e7aa54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
